Hack to use DIRECT_TO_TARGET_DIRECTORY
Otherwise it will fail with the following stacktrace, because directory
rename happens at commit time.

Query 20190206_000225_00000_ay4nj failed: Partition location does not exist: file:/var/folders/cs/tktg4_9j59g6m202z1sfr65xl7_b9w/T/PrestoTest534130696128938511/hive_data/tpch_bucketed/tmp_table_customer_49013716-cf2e-4c1b-bc86-977143cc1a2c
com.facebook.presto.spi.PrestoException: Partition location does not exist: file:/var/folders/cs/tktg4_9j59g6m202z1sfr65xl7_b9w/T/PrestoTest534130696128938511/hive_data/tpch_bucketed/tmp_table_customer_49013716-cf2e-4c1b-bc86-977143cc1a2c
	at com.facebook.presto.hive.util.HiveFileIterator$FileStatusIterator.processException(HiveFileIterator.java:163)
	at com.facebook.presto.hive.util.HiveFileIterator$FileStatusIterator.<init>(HiveFileIterator.java:133)
	at com.facebook.presto.hive.util.HiveFileIterator$FileStatusIterator.<init>(HiveFileIterator.java:118)
	at com.facebook.presto.hive.util.HiveFileIterator.getLocatedFileStatusRemoteIterator(HiveFileIterator.java:107)
	at com.facebook.presto.hive.util.HiveFileIterator.computeNext(HiveFileIterator.java:100)
	at com.facebook.presto.hive.util.HiveFileIterator.computeNext(HiveFileIterator.java:37)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at com.google.common.collect.Iterators.addAll(Iterators.java:357)
...........

Setting (from HiveQueryRunner)

use hive_bucketed.tpch_bucketed;

set session colocated_join=true;
set session redistribute_writes=false;
set session hive_bucketed.statistics_enabled=false;
set session hive_bucketed.collect_column_statistics_on_write=false;

CREATE TABLE hahagu
AS
SELECT a.totalprice, a.orderdate, b.phone
FROM hive_bucketed.tpch.orders @{bucket_count = 123} a
    JOIN hive_bucketed.tpch.customer @{bucket_count = 123} b
    ON a.custkey = b.custkey;